# Change these first
owner: MatrixDai # Your GitHub organization or username, where this repository lives
repo: xcar-upptime # The name of this repository

sites:
  - name: 【生产】消息服务（36.134.59.197）
    url: http://36.134.59.197:9090/q/health/ready
  - name: 【生产】MQTT服务（36.134.59.197）
    check: "tcp-ping"
    url: 36.134.59.197
    port: 1883
  - name: 【测试】消息服务（36.134.184.139）
    url: http://36.134.184.139:9090/q/health/ready
  - name: 【测试】MQTT服务（36.134.184.139）
    check: "tcp-ping"
    url: 36.134.184.139
    port: 1883

status-website:
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: 系统状态
  introTitle: "**猫眼** 叉车监管系统状态监控页面"
  introMessage: 系统状态
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
